// ============================================================================
// URL Lens - Public Share Page
// ============================================================================

import { createServerSupabaseClient } from '@/lib/supabase/server';
import { Box, Container, Typography, Paper, Alert } from '@mui/material';
import { SharedResultDisplay } from '@/components/SharedResultDisplay';

interface SharePageProps {
  params: Promise<{ id: string }>;
}

export default async function SharePage({ params }: SharePageProps) {
  const { id } = await params;

  // Fetch the shared analysis
  const supabase = await createServerSupabaseClient();
  const { data: analysis, error } = await supabase
    .from('url_analyses')
    .select('*')
    .eq('share_id', id)
    .single();

  if (error || !analysis) {
    return (
      <Container maxWidth="md" sx={{ py: 8 }}>
        <Alert severity="error">
          This shared report was not found or has been removed.
        </Alert>
      </Container>
    );
  }

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: '#f8fafc', py: 4 }}>
      <Container maxWidth="lg">
        {/* Header */}
        <Paper sx={{ p: 3, mb: 3 }}>
          <Typography variant="h4" fontWeight={700} gutterBottom>
            URL Scrapability Report
          </Typography>
          <Typography variant="body2" color="text.secondary">
            Shared on {new Date(analysis.created_at).toLocaleDateString('en-US', {
              year: 'numeric',
              month: 'long',
              day: 'numeric',
            })}
          </Typography>
        </Paper>

        {/* Analysis Result */}
        <SharedResultDisplay analysis={analysis} />

        {/* Footer */}
        <Box sx={{ mt: 4, textAlign: 'center' }}>
          <Typography variant="body2" color="text.secondary">
            Generated by{' '}
            <Typography
              component="a"
              href="/"
              sx={{ color: 'primary.main', textDecoration: 'none' }}
            >
              URL Lens
            </Typography>
            {' '}- URL Scrapability Analyzer
          </Typography>
        </Box>
      </Container>
    </Box>
  );
}
